export const routes = {
    home: "/",
    error: "/*",
    login: "/login",
    movies: "/movies/:category",
    searchPage: "/search/:search",
    registration: "/registration",
    movieDetails: "/movie/:movieId",
    moviesCategory: {
        popular: "/movies/popular",
        upcoming: "/movies/upcoming",
        topRated: "/movies/top_rated",
        nowPlaying: "/movies/now_playing",
    },
    tvDetails: "/tvPage/:tvId",
    tvShowes: "/tvShowes/:category",
    tvShowesCategory: {
        popular: "/tvShowes/popular",
        onTv: "/tvShowes/on_the_air",
        topRated: "/tvShowes/top_rated",
        airingToday: "/tvShowes/airing_today",
    },
    people: "/people",
    persone: "people/persone/:id",
};
