export const routes = {
    home: "FirstMovieProject/",
    error: "/*",
    login: "FirstMovieProject/login",
    movies: "FirstMovieProject/movies/:category",
    searchPage: "FirstMovieProject/search/:search",
    registration: "FirstMovieProject/registration",
    movieDetails: "FirstMovieProject/movie/:movieId",
    moviesCategory: {
        popular: "FirstMovieProject/movies/popular",
        upcoming: "FirstMovieProject/movies/upcoming",
        topRated: "FirstMovieProject/movies/top_rated",
        nowPlaying: "FirstMovieProject/movies/now_playing",
    },
    tvDetails: "FirstMovieProject/tvPage/:tvId",
    tvShowes: "FirstMovieProject/tvShowes/:category",
    tvShowesCategory: {
        popular: "FirstMovieProject/tvShowes/popular",
        onTv: "FirstMovieProject/tvShowes/on_the_air",
        topRated: "FirstMovieProject/tvShowes/top_rated",
        airingToday: "FirstMovieProject/tvShowes/airing_today",
    },
    people: "FirstMovieProject/people",
    persone: "FirstMovieProject/people/persone/:id",
};
